export const initialSessions = [
  {
    id: 'PS-7781',
    person: 'Ravi Kumar',
    email: 'rkumar@bankbm.in',
    ticket: 'CHG-2041',
    target: 'recon_db',
    engine: 'PostgreSQL 15',
    binding: 'Linked',
    confidence: 'Exact',
    baseRisk: 8,
    mlRisk: 8,
    control: 'In scope',
    status: 'active',
    started: '02:17:04',
    changeClass: 'RECON_MAINTENANCE',
    reasons: ['Known device', 'Inside approved window', 'Normal object breadth'],
    ip: '10.4.2.17',
    device: 'LT-4432',
    events: 214,
  },
  {
    id: 'PS-7814',
    person: 'Ananya Shah',
    email: 'ashah@bankbm.in',
    ticket: 'CHG-2078',
    target: 'payments_core',
    engine: 'Oracle 19c',
    binding: 'Linked',
    confidence: 'Exact',
    baseRisk: 18,
    mlRisk: 87,
    control: 'Step-up required',
    status: 'elevated',
    started: '02:22:11',
    changeClass: 'PAYMENTS_PATCH',
    reasons: ['New device', 'Access at 02:40, outside personal norm', 'Table breadth 4.1× peer median'],
    ip: '10.7.11.93',
    device: 'UNSEEN-93AF',
    events: 146,
  },
  {
    id: 'LEG-0019',
    person: 'dba_legacy',
    email: 'dba_legacy@bankbm.in',
    ticket: null,
    target: 'recon_db',
    engine: 'PostgreSQL 13',
    binding: 'Unlinked',
    confidence: 'None',
    baseRisk: 94,
    mlRisk: 91,
    control: 'Unknown',
    status: 'unlinked',
    started: '02:31:26',
    changeClass: 'NONE',
    reasons: ['No approved change binding', 'Direct database connection', 'Standing privileged account'],
    ip: '172.18.4.62',
    device: 'UNMANAGED',
    events: 33,
  },
  {
    id: 'PS-7820',
    person: 'Vikram Mehta',
    email: 'vmehta@bankbm.in',
    ticket: 'CHG-2084',
    target: 'treasury_dw',
    engine: 'PostgreSQL 16',
    binding: 'Linked',
    confidence: 'Exact',
    baseRisk: 12,
    mlRisk: 31,
    control: 'Enhanced logging',
    status: 'active',
    started: '02:36:42',
    changeClass: 'DW_READ_ONLY',
    reasons: ['Normal time window', 'Known device', 'Read volume at 89th percentile'],
    ip: '10.5.8.41',
    device: 'LT-5841',
    events: 89,
  },
  {
    id: 'PS-7827',
    person: 'Neha Iyer',
    email: 'niyer@bankbm.in',
    ticket: 'CHG-2091',
    target: 'customer_360',
    engine: 'PostgreSQL 16',
    binding: 'Linked',
    confidence: 'Heuristic',
    baseRisk: 34,
    mlRisk: 54,
    control: 'Observe',
    status: 'active',
    started: '02:41:19',
    changeClass: 'C360_SUPPORT',
    reasons: ['Heuristic ticket correlation', 'New IP subnet', 'Commands remain in scope'],
    ip: '10.12.3.16',
    device: 'LT-2016',
    events: 57,
  },
]

export const initialCases = [
  { id: 'CASE-1842', sessionId: 'LEG-0019', title: 'Unlinked legacy DBA session', severity: 'Critical', owner: 'SOC Queue', status: 'Open', age: '3m' },
  { id: 'CASE-1838', sessionId: 'PS-7799', title: 'Native denial on raw customer table', severity: 'Medium', owner: 'Priya Menon', status: 'Investigating', age: '18m' },
  { id: 'CASE-1821', sessionId: 'PS-7751', title: 'Ticket expired during active session', severity: 'High', owner: 'Arjun Rao', status: 'Contained', age: '1h' },
]

export const attestations = [
  { id: 'ATT-CHG-2041-PS7781', change: 'CHG-2041', actor: 'Ravi Kumar', events: 214, verdict: 'VERIFIED', sealed: '02:59:04', delayed: false },
  { id: 'ATT-CHG-2067-PS7799', change: 'CHG-2067', actor: 'Mihir Das', events: 88, verdict: 'VERIFIED', sealed: '02:44:31', delayed: false },
  { id: 'ATT-CHG-2052-PS7774', change: 'CHG-2052', actor: 'Sana Khan', events: 173, verdict: 'GAP', sealed: '01:58:17', delayed: true },
]

export const timelineSeed = [
  { label: 'Approved ticket', detail: 'CHG-2078', time: '02:16:58', state: 'done' },
  { label: 'JIT role issued', detail: 'DB_PATCH_WRITE', time: '02:17:04', state: 'done' },
  { label: 'pgAudit stream', detail: 'Started', time: '02:22:11', state: 'progress' },
  { label: 'Anomaly detected', detail: 'Risk 87', time: '02:39:58', state: 'alert' },
  { label: 'MFA required', detail: 'Pending', time: '—', state: 'progress' },
  { label: 'Attestation pending', detail: 'Evidence sealing', time: '—', state: 'pending' },
]

export function riskFor(session, mode) {
  if (mode === 'rules') return session.baseRisk
  if (mode === 'ml') return session.mlRisk
  return Math.max(session.baseRisk, session.mlRisk)
}
